
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-rakugaki-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./data/ai_rakugaki_db.sqlite3
      - OTHER_ENV_VARS=値 # 必要に応じて追加
    volumes:
      - backend_data:/app/saved-images
      - backend_generated:/app/generated-images
      - backend_db:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    # 内部ネットワークに参加
    networks:
      - internal_network
    # ポート公開を削除（内部通信のみ）
    # ports:
    #   - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-rakugaki-frontend
    restart: unless-stopped
    ports:
      - "3000:3000" # フロントエンドのみホストに公開
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - OTHER_ENV_VARS=値 # 必要に応じて追加
    depends_on:
      - backend
    networks:
      - internal_network

volumes:
  backend_data:
  backend_generated:
  backend_db:

networks:
  internal_network:
    driver: bridge
