
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-rakugaki-backend
    restart: unless-stopped
    ports:
      - "8000:8000"  # ホストの8000ポートをコンテナの8000ポートにマッピング
    environment:
      - DATABASE_URL=sqlite:///./data/ai_rakugaki_db.sqlite3
      - OTHER_ENV_VARS=値 # 必要に応じて追加
    volumes:
      - backend_data:/app/saved-images
      - backend_generated:/app/generated-images
      - backend_db:/app/data
    gpus: all  # GPUサポートを有効にする

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-rakugaki-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # フロントエンドのみホストに公開
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - OTHER_ENV_VARS=値 # 必要に応じて追加
    depends_on:
      - backend

volumes:
  backend_data:
  backend_generated:
  backend_db:
